### ISSUE TITLE
有时候为什么提交的json需要带上referer的啊？

### ISSUE THREAD

**Issue by miranda0111** [ygxiuming/Lecture-registration#1]

**Comment by ygxiuming** [comment]
> _未提供说明。_

这跟微信程序 报名工具的认证有关，若有认证的将会生成refer，通过refer可以在浏览器进行操作，在提交表单的时候携带refer。
但是经过我的测试，不带refer也可以正常提交。refer不是必填选项。

其中提交表单最重要的只有两项，一个是items，另一个是info，这两个出错将会导致提交失败，其他的参数都不是特别重要的。

**Comment by miranda0111** [comment]
好的好的，感谢回复，已经手搓了个多账号版本了~~
