### ISSUE TITLE
这个有时候抓detail的eid是错的刚好报错了一次

### ISSUE THREAD

**Issue by miranda0111** [ygxiuming/Lecture-registration#2]
>![](https://s1.328888.xyz/2022/09/28/sYbjC.jpg)

**Comment by ygxiuming** [comment]
> > ![](https://camo.githubusercontent.com/3b192ebff1f9578d1ac47af3f06af2795469c4bf6dffa914d4d19a6924531647/68747470733a2f2f73312e3332383838382e78797a2f323032322f30392f32382f7359626a432e6a7067)

我没有碰到过这种情况，若是这种错误是偶然产生的话，我的解决方法是这样的。
利用try进行捕获错误，并进行重发，对返回的json数据进行判断。

若不是偶然的话，大概率是某种编码，尝试进行反编译，模拟编码
